config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'welcome/index'

  resources :guests do
    resources :plus_ones
    member do
      get :confirm
      patch :complete
    end
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
# frozen_string_literal: true

#
# ActiveAdmin console user.
#
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
# frozen_string_literal: true

#
# A guest or plus one.
#
class Attendee < ApplicationRecord
  scope :diet?, -> { where.not(diet: nil) }
  scope :child?, -> { where(child: true) }
end

app/models/concerns/findable_with_token.rb
# frozen_string_literal: true

#
# Make a model findable only when a secure token is provided.
#
module FindableWithToken
  extend ActiveSupport::Concern

  ID_TOKEN_RX = /\A(\d+)-(\w+)\z/.freeze

  included do
    has_secure_token

    def to_param
      id ? "#{id}-#{token}" : nil
    end

    def self.find_by_id_token(id_token)
      raise ActiveRecord::RecordNotFound unless id_token =~ ID_TOKEN_RX

      id = Regexp.last_match(1)
      token = Regexp.last_match(2)

      record = find(id)
      raise ActiveRecord::RecordNotFound unless
        ActiveSupport::SecurityUtils.secure_compare(record.token, token)

      record
    end
  end
end

app/models/guest.rb
# frozen_string_literal: true

#
# A primary guest.
#
class Guest < ApplicationRecord
  include FindableWithToken

  auto_strip_attributes :email, :first_name, :last_name, :diet, :songs, :notes

  validates :email, presence: true, uniqueness: true
  validates :email, format: Devise.email_regexp, allow_blank: true

  validates :first_name, presence: true, if: :persisted?
  validates :first_name, length: { maximum: 1024 }
  validates :last_name, presence: true, if: :persisted?
  validates :last_name, length: { maximum: 1024 }

  def name
    "#{first_name} #{last_name}"
  end

  def name_with_email
    "#{name} <#{email}>"
  end

  # Don't allow long or odd names in emails; may be spam.
  def email_safe_salutation
    return 'Hello,' if
      first_name.blank? || first_name !~ /\A[\p{Word}\s'-]{1,30}\z/i

    "Dear #{first_name},"
  end

  validates :diet, length: { maximum: 8192 }
  validates :songs, length: { maximum: 8192 }
  validates :notes, length: { maximum: 8192 }

  has_many :plus_ones, dependent: :destroy

  scope :confirmed, -> { where.not(confirmed_at: nil) }
  scope :attending, -> { confirmed.where(attending: true) }
  scope :not_attending, -> { confirmed.where(attending: false) }
end

app/models/plus_one.rb
# frozen_string_literal: true

#
# An extra guest.
#
class PlusOne < ApplicationRecord
  belongs_to :guest

  auto_strip_attributes :first_name, :last_name, :diet

  validates :first_name, presence: true
  validates :first_name, length: { maximum: 1024 }
  validates :last_name, presence: true
  validates :last_name, length: { maximum: 1024 }

  def name
    "#{first_name} #{last_name}"
  end

  validates :diet, length: { maximum: 8192 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  if ENV['BASIC_AUTH_NAME'] && ENV['BASIC_AUTH_PASSWORD']
    http_basic_authenticate_with \
      name: ENV['BASIC_AUTH_NAME'],
      password: ENV['BASIC_AUTH_PASSWORD']
  end
end

app/controllers/guests_controller.rb
# frozen_string_literal: true

class GuestsController < ApplicationController
  def new
    respond_to :html

    @guest = Guest.new
  end

  def create
    respond_to :html

    @guest = Guest.new(guest_params)
    unless ENV['RECAPTCHA_SECRET_KEY'].blank? || verify_recaptcha(model: @guest)
      render :new
      return
    end

    if @guest.save
      redirect_to guest_path(@guest)
    else
      existing_guest = Guest.find_by(email: guest_params[:email])
      if existing_guest
        @guest = existing_guest
        GuestMailer.welcome_back_email(@guest).deliver_now
        render :new_exists
      else
        render :new
      end
    end
  end

  def show
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
  end

  def update
    @guest = Guest.find_by_id_token(params[:id])

    if @guest.update(guest_params)
      if @guest.attending?
        redirect_to guest_plus_ones_path(@guest)
      else
        redirect_to confirm_guest_path(@guest)
      end
    else
      render :show
    end
  end

  def confirm
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
  end

  def complete
    respond_to :html

    @guest = Guest.find_by_id_token(params[:id])
    Guest.transaction do
      @guest.update!(guest_params)
      @guest.touch :confirmed_at
    end
    GuestMailer.confirmation_email(@guest).deliver_now
  end

  private

  def guest_params
    params.require(:guest).permit(
      :email, :first_name, :last_name, :attending, :diet, :songs, :notes
    )
  end
end

app/controllers/plus_ones_controller.rb
# frozen_string_literal: true

class PlusOnesController < ApplicationController
  before_action do
    @guest = Guest.find_by_id_token(params[:guest_id])
  end

  def new
    respond_to :html
    @plus_one = @guest.plus_ones.new
  end

  def create
    respond_to :html
    @plus_one = @guest.plus_ones.new(plus_one_params)
    if @plus_one.save
      redirect_to guest_plus_ones_path(@guest)
    else
      render :new
    end
  end

  def index
    respond_to :html
    @plus_ones = @guest.plus_ones.order(:first_name, :last_name)
  end

  def edit
    @plus_one = @guest.plus_ones.find(params[:id])
    respond_to :html
  end

  def update
    @plus_one = @guest.plus_ones.find(params[:id])

    if @plus_one.update(plus_one_params)
      redirect_to guest_plus_ones_path(@guest)
    else
      render :edit
    end
  end

  def destroy
    respond_to :html
    @plus_one = @guest.plus_ones.find_by(id: params[:id])
    @plus_one&.destroy
    redirect_to guest_plus_ones_path(@guest)
  end

  private

  def plus_one_params
    params.require(:plus_one).permit(:first_name, :last_name, :diet, :child)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @google_maps_url = 'https://goo.gl/maps/nBAxNAsmPSS2'
    @cool_earth_url = 'https://www.coolearth.org/'
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(key)
    case key
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end

  def errors_for(object)
    return unless object.errors.any?

    content_tag(:div, class: 'mb-3 card border-danger') do
      concat(content_tag(:div, class: 'card-header bg-danger text-white') do
        concat "Oops, #{pluralize(object.errors.count, 'problem')}:"
      end)
      concat(content_tag(:ul, class: 'mb-0 list-group list-group-flush') do
        object.errors.full_messages.each do |msg|
          concat content_tag(:li, msg, class: 'list-group-item')
        end
      end)
    end
  end
end

app/helpers/guests_helper.rb
# frozen_string_literal: true

module GuestsHelper
end

app/helpers/plus_ones_helper.rb
# frozen_string_literal: true

module PlusOnesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/application/_mailing_address.html.erb
<strong>Alert</strong><br>
Qikiqtaaluk Region, Nunavut<br>
Canada<br>

app/views/application/_wedding_address.html.erb
<strong>Halley Research Station</strong><br>
Brunt Ice Shelf<br>
Antarctica

app/views/guests/_dietary_preferences.html.erb
<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :diet, 'Dietary Preferences', class: 'col-form-label' %>
  </div>
  <div class="col-md-9">
    <%= form.text_area :diet, id: "#{id_stem}_diet", class: 'form-control' %>
    <small class="form-text text-muted">For example, vegan, vegetarian, gluten free, and any allergies or intolerances.</small>
  </div>
</div>

app/views/guests/_leader.html.erb
<div id="guests-leader" class="jumbotron text-center">
  <div class="container">
    <h1>RSVP</h1>
  </div>
</div>

app/views/guests/_name.html.erb
<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :first_name, 'First Name', class: 'col-form-label' %>
    <span class="wedding-required">*</span>
  </div>
  <div class="col-md-9">
    <%= form.text_field :first_name, id: "#{id_stem}_first_name", class: 'form-control', autofocus: true, required: true %>
  </div>
</div>

<div class="form-group row">
  <div class="col-md-3">
    <%= form.label :last_name, 'Last Name', class: 'col-form-label' %>
    <span class="wedding-required">*</span>
  </div>
  <div class="col-md-9">
    <%= form.text_field :last_name, id: "#{id_stem}_last_name", class: 'form-control', required: true %>
  </div>
</div>

app/views/guests/_rsvp_nav.html.erb
<nav class="guests-rsvp-nav">
  <ul class="nav nav-pills nav-fill">
    <li class="nav-item">
      <%= link_to '1. About You', guest_path(@guest), class: ['nav-link', active == 1 ? 'active' : ''] %>
    </li>
    <li class="nav-item">
      <% if active >= 2 %>
        <%= link_to '2. Plus Ones', guest_plus_ones_path(@guest), class: ['nav-link', active == 2 ? 'active' : ''] %>
      <% else %>
        <a class="nav-link <%= active == 2 ? 'active' : '' %>">2. Plus Ones</a>
      <% end %>
    </li>
    <li class="nav-item">
      <% if active >= 3 %>
        <%= link_to '3. Confirm', confirm_guest_path(@guest), class: ['nav-link', active == 3 ? 'active' : ''] %>
      <% else %>
        <a class="nav-link <%= active == 3 ? 'active' : '' %>">3. Confirm</a>
      <% end %>
    </li>
  </ul>
</nav>

app/views/guests/complete.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <h2>Thanks!</h2>
      <p>We've sent an email confirmation to <tt><%= @guest.email %></tt>.</p>
      <p>If you don't receive the email within a few minutes, please check your spam folder, and if it's not there <%= mail_to ENV['CONTACT_EMAIL'], 'contact us' %>.</p>
      <p>The email contains a link that you can use to update your RSVP later if you need to.</p>
      <p><%= link_to 'Back to the Home Page', root_path %></p>
    </div>
  </div>
</div>

app/views/guests/confirm.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <%= render partial: 'rsvp_nav', locals: { active: 3 } %>

      <h2>Confirm</h2>

      <%= form_with(model: @guest, url: complete_guest_path(@guest), local: true) do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <% if @guest.attending? %>
      <h3>Your Details</h3>
      <div class="card mb-3">
        <h5 class="card-header"><%= @guest.name %></h5>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              Email
            </div>
            <div class="col-md-8">
              <p><tt><%= @guest.email %></tt></p>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              Dietary Preferences
            </div>
            <div class="col-md-8">
              <% if @guest.diet.present? %>
                <pre><%= @guest.diet %></pre>
              <% else %>
                <p>(None)</p>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              Song Suggestions
            </div>
            <div class="col-md-8">
              <% if @guest.songs.present? %>
                <pre><%= @guest.songs %></pre>
              <% else %>
                <p>(None)</p>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12 text-right">
              <%= link_to 'Edit', guest_path(@guest), class: 'card-link', data: { disable_with: 'Loading...' } %>
            </div>
          </div>
        </div>
      </div>

      <h3>Plus Ones</h3>
      <% if @guest.plus_ones.any? %>
        <%= render @guest.plus_ones %>
      <% else %>
        <p>(None &mdash; just you.)</p>
      <% end %>
      <% else %>
      <p>Sorry to hear you won't be joining us!</p>
      <h3>Your Details</h3>
      <div class="card mb-3">
        <h5 class="card-header"><%= @guest.name %></h5>
        <div class="card-body">
          <div class="row">
            <div class="col-md-4">
              Email
            </div>
            <div class="col-md-8">
              <p><tt><%= @guest.email %></tt></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>

      <h3>Other Comments?</h3>

      <%= form.text_area :notes, class: 'form-control' %>
      <small class="form-text text-muted">Anything else you'd like to let us know?</small>

      <div class="row guests-buttons">
        <div class="offset-md-3 col-md-6 text-center">
          <%= form.submit 'Complete RSVP', class: 'btn btn-primary', data: { disable_with: 'Sending...' } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/guests/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <p>Please enter your email address to begin. We'll send you an email with important information once you have RSVP'd.</p>
      <%= form_with scope: :guest, url: guests_path, local: true do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :email, class: 'col-form-label' %>
        </div>
        <div class="col-md-9">
          <%= form.email_field :email, id: 'guest_email', class: 'form-control', autofocus: true, required: true %>
        </div>
      </div>

      <div class="row guests-buttons">
        <div class="offset-md-3 col-md-6 text-center">
          <%- if ENV['RECAPTCHA_SECRET_KEY'].blank? -%>
          <%= form.submit 'Continue', class: 'btn btn-primary', data: { disable_with: 'Sending...' } %>
          <%- else -%>
          <%= invisible_recaptcha_tags text: 'Continue', class: 'btn btn-primary', data: { disable_with: 'Sending...' } %>
          <%- end -%>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/guests/new_exists.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <h2>Welcome Back</h2>
      <p>It looks like you've already registered your RSVP, so we've sent you an email with a link that you can use to update it.</p>
      <p>Please check your <tt><%= @guest.email %></tt> email including spam folders!</p>
      <p>If you don't receive the email, please <%= mail_to ENV['CONTACT_EMAIL'], 'contact us' %>.</p>
    </div>
  </div>
</div>

app/views/guests/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'leader' %>
      <%= render partial: 'rsvp_nav', locals: { active: 1 } %>

      <h2>About You</h2>

      <%= form_with(model: @guest, method: :patch, local: true, id: 'guest-edit-form') do |form| %>
      <div class="row">
        <div class="col-md-12">
          <%= errors_for(@guest) %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :email, class: 'col-form-label' %>
          <span class="wedding-required">*</span>
        </div>
        <div class="col-md-9">
          <%= form.email_field :email, id: 'guest_email', class: 'form-control', required: true %>
        </div>
      </div>

      <%= render partial: 'name', locals: { form: form, id_stem: 'guest' } %>

      <div class="form-group row">
        <div class="offset-md-3 col-md-9">
          <p><strong>Will you be joining us?</strong></p>
          <div class="form-check form-check-inline">
            <%= form.radio_button :attending, 'true', checked: true, id: 'guest_attending_true', class: 'form-check-input' %>
            <%= form.label :attending, 'Yes', value: 'true', class: 'form-check-label' %>
          </div>
          <div class="form-check form-check-inline">
            <%= form.radio_button :attending, 'false', id: 'guest_attending_false', class: 'form-check-input' %>
            <%= form.label :attending, 'No', value: 'false', class: 'form-check-label' %>
          </div>
        </div>
      </div>

      <div class="guest-attending-only">
      <%= render partial: 'dietary_preferences', locals: { form: form, id_stem: 'guest' } %>

      <div class="form-group row">
        <div class="col-md-3">
          <%= form.label :songs, 'Song Suggestions', class: 'col-form-label' %>
        </div>
        <div class="col-md-9">
          <%= form.text_area :songs, id: 'guest_songs', class: 'form-control' %>
          <small class="form-text text-muted">We're crowd sourcing our playlist! Choose some songs you'd like to hear.</small>
        </div>
      </div>
      </div>

      <div class="row guests-buttons">
        <div class="col-md-3">
          <span class="wedding-required">* Required</span>
        </div>
        <div class="col-md-6 text-center">
          <%= form.submit 'Continue', class: 'btn btn-primary', data: { disable_with: 'Sending...' } %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t :wedding_name %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="noindex, nofollow">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, class: flash_class(key)) do -%>
        <%= value %>
      <% end -%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/plus_ones/_form.html.erb
<%= form_with(model: [@guest, @plus_one], local: true) do |form| %>
  <div class="row">
    <div class="col-md-12">
      <%= errors_for(@plus_one) %>
    </div>
  </div>

  <%= render partial: 'guests/name', locals: { form: form, id_stem: 'plus_one' } %>

  <%= render partial: 'guests/dietary_preferences', locals: { form: form, id_stem: 'plus_one' } %>

  <div class="form-group row">
    <div class="offset-md-3 col-md-9">
      <div class="form-check form-check-inline">
        <%= form.check_box :child, id: 'plus_one_child', class: 'form-check-input' %>
        <%= form.label :child, 'Child (12 or under)', class: 'form-check-label' %>
      </div>
    </div>
  </div>

  <div class="row guests-buttons">
    <div class="col-md-3">
      <span class="wedding-required">* Required</span>
    </div>
    <div class="col-md-6 text-center">
      <%= form.submit submit_action, class: 'btn btn-primary', data: { disable_with: 'Sending...' } %>
    </div>
    <div class="col-md-3 text-right">
      <%= link_to 'Cancel', guest_plus_ones_path(@guest), class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/plus_ones/_plus_one.html.erb
<div class="card mb-3">
  <h5 class="card-header"><%= plus_one.name %></h5>
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        Dietary Preferences
      </div>
      <div class="col-md-8">
        <% if plus_one.diet.present? %>
          <pre><%= plus_one.diet %></pre>
        <% else %>
          <p>(None)</p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        Child
      </div>
      <div class="col-md-8">
        <p><%= plus_one.child ? 'Yes' : 'No' %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-right">
        <%= link_to 'Edit', edit_guest_plus_one_path(plus_one.guest, plus_one), class: 'card-link', data: { disable_with: 'Loading...' } %>
        <%= link_to 'Remove', guest_plus_one_path(plus_one.guest, plus_one), method: :delete, class: 'card-link', data: { disable_with: 'Removing...', confirm: 'Are you sure?' } %>
      </div>
    </div>
  </div>
</div>

app/views/plus_ones/edit.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Edit Plus One</h2>
      <%= render partial: 'form', locals: { submit_action: 'Save Plus One' } %>
    </div>
  </div>
</div>

app/views/plus_ones/index.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Plus Ones</h2>
      <p>Please let us know below if you're bringing someone else to the wedding. Children are also very welcome.
      <p>&nbsp;</p>

      <% if @plus_ones.any? %>
        <%= render @plus_ones %>
      <% else %>
        <p>No plus ones added yet. Flying solo.</p>
      <% end %>
      <p>
        <%= link_to 'Add Plus One', new_guest_plus_one_path(@guest), class: 'btn btn-primary', data: { disable_with: 'Loading...' } %>
      </p>

      <p>&nbsp;</p>
      <p class="guests-buttons">
        <%= link_to 'Continue', confirm_guest_path(@guest), class: 'btn btn-primary' %>
      </p>
    </div>
  </div>
</div>

app/views/plus_ones/new.html.erb
<div class="container">
  <div class="row">
    <div class="offset-lg-2 col-lg-8">
      <%= render partial: 'guests/leader' %>
      <%= render partial: 'guests/rsvp_nav', locals: { active: 2 } %>

      <h2>Add Plus One</h2>
      <%= render partial: 'form', locals: { submit_action: 'Add Plus One' } %>
    </div>
  </div>
</div>

app/views/welcome/_calendar_svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 8 8">
  <path d="M0 0v2h7v-2h-7zm0 3v4.91c0 .05.04.09.09.09h6.81c.05 0 .09-.04.09-.09v-4.91h-7zm1 1h1v1h-1v-1zm2 0h1v1h-1v-1zm2 0h1v1h-1v-1zm-4 2h1v1h-1v-1zm2 0h1v1h-1v-1z" />
</svg>

app/views/welcome/_footer.html.erb
<footer id="welcome-index-footer" class="page-footer">
  <div class="container-fluid">
    <div class="row">
      <div id="welcome-index-footer-cta" class="col-md-12 text-center">
        <%= link_to 'RSVP TODAY!', new_guest_path, class: 'btn btn-primary wedding-cta-btn' %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center" id="welcome-index-footer-credits">
        <small><% t :photo_credits %></small>
      </div>
    </div>
  </div>
</footer>

app/views/welcome/_jumbo.html.erb
<section id="welcome-index-leader" class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><%= t :wedding_couple_names %></h1>
    <p class="leader-date">
      <%= t :wedding_date %>, <%= t :wedding_location %>
    </p>
    <p>
      <%= link_to 'RSVP TODAY!', new_guest_path, class: 'btn btn-primary wedding-cta-btn' %>
    </p>
  </div>
</section>

app/views/welcome/_map_marker_svg.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 8 8">
  <path d="M3 0c-1.66 0-3 1.34-3 3 0 2 3 5 3 5s3-3 3-5c0-1.66-1.34-3-3-3zm0 1c1.11 0 2 .9 2 2 0 1.11-.89 2-2 2-1.1 0-2-.89-2-2 0-1.1.9-2 2-2z" transform="translate(1)" />
</svg>

app/views/welcome/_plan.html.erb
<section id="welcome-index-wedding-plan-leader" class="jumbotron text-center">
  <div class="container">
    <h1>The Plan</h1>
  </div>
</section>
<section id="welcome-index-wedding-plan">
  <div class="container">
    <div class="row">
      <div class="offset-md-3 col-md-6">
        <h2>Order of the Day</h2>
        <p><strong>12:30pm</strong> &mdash; Guests arrive</p>
        <p><strong>1pm</strong> &mdash; Wedding service</p>
        <p><strong>1:30pm</strong> &mdash; Cocktails, photos, confetti and canapes</p>
        <p><strong>3pm-6pm</strong> &mdash; Food and drink</p>
        <p><strong>7pm</strong> &mdash; Cutting of the cake! Drinking, dancing!</p>
        <p><strong>12am</strong> &mdash; Bar closes</p>
        <p>There will be a tab for the evening, followed by a cash bar.</p>
        <p><strong>Dress code</strong> is warm.</p>
        <h2>Gifts &amp; Cards</h2>
        <p>We'd be pleased if you made a donation to charity rather than bringing a gift. Our goal is to raise £1,000 for <%= link_to 'Cool Earth', @cool_earth_url %>, the non-profit that works alongside rainforest communities to halt deforestation and climate change.</p>
        <p class="text-center"><%= link_to 'Donate to Cool Earth', @cool_earth_url, class: 'btn btn-primary wedding-cta-btn' %></p>
        <p>If you'd like to send us a card, we'll send you our mailing address by email once you RSVP.</p>
        <h2>Menu</h2>
        <p><strong>Starter</strong> &mdash; Home Cured Salmon Gravadlax with Horseradish Cream &amp; Beetroot Tart <sup>*</sup> &dagger;</p>
        <p><strong>Main</strong> &mdash; Fricassee of Chicken with Lyonnaise Potato &ddagger;</p>
        <p><strong>Dessert</strong> &mdash; Choux Swan with Chocolate & Brandy Sauce <sup>&sect;</sup></p>
        <p><strong>Children's Menu</strong>: Garlic bread, chicken goujons and chips, ice cream.</p>
        <ul class="list-unstyled">
          <li><small><sup>*</sup> Gluten free &amp; vegan starter: Tomato soup</small></li>
          <li><small>&dagger; Gluten free &amp; dairy free starter: Gravadlax served without tart</small></li>
          <li><small>&ddagger; Main is gluten free. Vegan main: Aubergine &amp; Black Bean Chilli with Cumin Rice</small></li>
          <li><small><sup>&sect;</sup> Vegan, gluten free &amp; dairy free dessert: Fruit platter</small></li>
        </ul>
        <p>The venue is making every effort to cater for vegan, vegetarian, gluten free, allergies and other dietary preferences, as indicated in your RSVPs.</p>
        <h2>RSVPs</h2>
        <p>Please RSVP as soon as possible, so we know who is coming and can make sure we keep a seat and a piece of cake for you if you can come! If it turns out you can’t make it, please let us know as soon as you can.</p>
      </div>
    </div>
  </div>
</section>